### ISSUE TITLE
Any plans to bump version?

### ISSUE THREAD

**Issue by CardboardTurkey** [danyspin97/wpaperd#26]
There have been a few fixes released since `0.2.0`, e.g. #10, #24. Seems like a `0.2.1` would be appropriate.

**Comment by danyspin97** [comment]
Hello @CardboardTurkey and thank you for the question. Yea, I am planning to bump the version and I was waiting for smithay-client-toolkit to do the same so that I can publish wpaperd to crates.io (to my knowledge, dependencies on git repositories are now allowed). Since this hasn't happened in the last months, I am going to bump it anyway this week.

**Comment by CardboardTurkey** [comment]
Thanks good thanks. I'm keen to update to latest version in nixpkgs

**Comment by danyspin97** [comment]
A new version`0.3.0` has been released 😄  Let me know if you have any issue!
