### ISSUE TITLE
Randomize through folder without repeats

### ISSUE THREAD

**Issue by daqnal** [danyspin97/wpaperd#39]
Just a quick suggestion:
Design some way for the random wallpaper sort to not repeat wallpapers until it has shown every one in the folder set by the user.
One solution would be to initialize a randomized list of every wallpaper's index, then move through that list every next time wpaperd is run.
Nice project 👍

**Comment by Nama** [comment]
Thank you!

Is the parameter really needed? Why not set it to amount of wallpapers in the folder?

**Comment by danyspin97** [comment]
Yea, the parameter is needed because of how the queue work. The queue is a fixed size vector and needs to be reallocated when the size change. If the queue was the same size as the amount of wallpapers in the folder, I would need to reallocate it often depending on the user habits.

Personally, I think that setting that amount to a reasonable amount (like ~200) would have almost the same effect, due to randomness. It is also possible to set a higher number than the amount of wallpapers, achieving the effect mentioned.
