### ISSUE TITLE
Match outputs using name or description

### ISSUE THREAD

**Issue by pjones** [danyspin97/wpaperd#90]
First off, thank you for this wonderful piece of software!

I would like to be able to match outputs using their name (what Sway calls the output ID) or their description (what Sway calls the output name).  For example, I want to have one set of wallpapers for an output port (e.g., `DP-4`) but want to use a different set when `DP-4` is connected to a specific monitor or projector (e.g., `Samsung Electric Company S32D850 0x304C3341`).

It seems like this can be accomplished by adding the output's description to the `DisplayInfo` struct and then replacing `Config.get_output_by_name` with a similar function that can find the output's configuration using either its name or its description.  Does that sound reasonable to you?

I don't have a lot of free time right now, but if the change only requires what I've outlined above I can probably send in a patch.

**Comment by danyspin97** [comment]
Hello @pjones !

> First off, thank you for this wonderful piece of software!

:) :)

> It seems like this can be accomplished by adding the output's description to the DisplayInfo struct and then replacing Config.get_output_by_name with a similar function that can find the output's configuration using either its name or its description. Does that sound reasonable to you?

I think this request makes a lot of sense and the proposed implementation sounds reasonable. I prefer to use a complete name so that it's easier than matching incomplete descriptions (like "Samsung").

> I don't have a lot of free time right now, but if the change only requires what I've outlined above I can probably send in a patch.

I think that is the only change required and some documentation (I can take care of the latter if you prefer), so please feel free to send a patch! :)
