### ISSUE TITLE
(Feature Request) Add option to save copy of current wallpaper

### ISSUE THREAD

**Issue by guttermonk** [danyspin97/wpaperd#93]
If there were an option for the daemon to save a copy of the wallpaper to a static file path when it transitions to a new image, the copied wallpaper could be used for the lockscreen.

BTW, I starred this repo since it's the best wallpaper app. Really comes closest out of the box to doing everything I want without any bloat. Keep up the great work!

**Comment by ryan77627** [comment]
I too would like this feature, since it seems to be the easiest way to set the current wallpaper to the background for hyprlock/others

**Comment by danyspin97** [comment]
Hello @guttermonk and @ryan77627 ! 

> BTW, I starred this repo since it's the best wallpaper app. Really comes closest out of the box to doing everything I want without any bloat. Keep up the great work!

Thank you :)

Regarding the feature, I am thinking between a `watch` command that waits until the wallpaper changes, leaving up to scripts to copy the wallpaper, or creating a symlink in `.local/state/wpaperd/wallpapers`:

```bash
$ ls .local/state/wpaperd/wallpapers
DP-4
eDP-1
```

Would that work with hyprlock and swaylock?

**Comment by guttermonk** [comment]
I haven't tried hyprlock, but either a copy or symlink at that path would work for swaylock.

I've also seen people use `.cache` for stuff like this. It may be preferable to also log to `.cache/wpaperd/` instead of `.local/state/wpaperd/` as well since people tend to back-up their `.local/` folder and there's no need to back-up logs typically. Just food for thought.

**Comment by ryan77627** [comment]
Same here for hyprlock, a copy or (preferably for me honestly) a symlink to the actual file named whatever the display is named would work just fine.

Maybe regarding the path we can just have a configuration value for it, that way people can choose where (and if) they go?

**Comment by danyspin97** [comment]
> well since people tend to back-up their .local/ folder and there's no need to back-up logs typically. Just food for thought.

I am not sure if this is good practice, `.local` contains many things that are not suited for backup afaik (mine contains installation from `cargo install`, python libraries from `pipx` and many other not needed stuff). I believe `.local/share` contains the important data to include in the backup, but that might differ depending on your setup.

> Maybe regarding the path we can just have a configuration value for it, that way people can choose where (and if) they go?

That is doable, but I think it's not needed at all and add quite a bit of complexity. You can always change the value of XDG_STATE_HOME and have the logs and the symlinks somewhere else. Otherwise, you could also create a symlink to the symlinks generated by wpaperd.
